CREATE MEMORY TABLE "PUBLIC"."NACE"(

    "ORDER_ID" BIGINT NOT NULL,

    "CODE" CHARACTER VARYING(255) NOT NULL,

    "CREATED_DATE_TIME" TIMESTAMP,

    "DESCRIPTION" CHARACTER VARYING(255) NOT NULL,

    "THIS_ITEM_ALSO_INCLUDES" CHARACTER VARYING(255),

    "THIS_ITEM_EXCLUDES" CHARACTER VARYING(255),

    "THIS_ITEM_INCLUDES" CHARACTER VARYING(255) NOT NULL,

    "LEVEL" INTEGER NOT NULL,

    "PARENT" CHARACTER VARYING(255),

    "REFERENCE_TO_ISIC_REV" CHARACTER VARYING(255) NOT NULL,

    "RULING" CHARACTER VARYING(255),

    "UPDATED_DATE_TIME" TIMESTAMP

);
ALTER TABLE "PUBLIC"."NACE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_2" PRIMARY KEY("ORDER_ID");